# Generated by Django 3.1.7 on 2021-03-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210326_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isbusiness',
            field=models.BooleanField(default=False),
        ),
    ]
