# Generated by Django 3.1.7 on 2021-03-25 11:46

import computed_property.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineCartApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', computed_property.fields.ComputedIntegerField(compute_from='calcprice', editable=False)),
                ('quantity', models.IntegerField(default=1)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodorders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='OnlineCartApp.Products')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
    ]
