# Generated by Django 3.1.7 on 2021-03-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['orderquantity']},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='quantity',
            new_name='orderquantity',
        ),
    ]
